
package main.java.com.programa_costos.gui;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.List;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.SwingUtilities;
import main.java.com.programa_costos.model.Producto;
import main.java.com.programa_costos.model.Proveedor;
import main.java.com.programa_costos.service.CostCalculator;
import main.java.com.programa_costos.service.ProveedorService;

/**
 *
 * @author bvillalobosromero
 */
public class InterfazGraficaMain extends javax.swing.JFrame {

    private static final String CONFIG_FILE = "config.txt";
    private static File selectFile = null;

    /**
     * Creates new form NewJFrame
     */
    public InterfazGraficaMain() {
        initComponents();
        Image icon = Toolkit.getDefaultToolkit().getImage(getClass().getClassLoader().getResource("img/icono_app.ico"));
        setIconImage(icon);
        
        selectFile = getSavedFile();

        if (selectFile == null) {
            textArchivo.setText("(No hay ruta seleccionada)");
        } else {
            textArchivo.setText("(Carpeta Seleccionada: " + selectFile.getName() + ")");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoSistemas = new javax.swing.ButtonGroup();
        grupoEspumas = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        textLargo = new javax.swing.JLabel();
        textoAncho = new javax.swing.JLabel();
        textAlto = new javax.swing.JLabel();
        textLogo = new javax.swing.JLabel();
        textGeneral = new javax.swing.JLabel();
        medAncho = new javax.swing.JTextField();
        medLargo = new javax.swing.JTextField();
        medAlto = new javax.swing.JTextField();
        textEspumas = new javax.swing.JLabel();
        botonCalcular = new javax.swing.JButton();
        tituloMedida = new javax.swing.JLabel();
        mecanizado = new javax.swing.JRadioButton();
        ciego = new javax.swing.JRadioButton();
        pasante = new javax.swing.JRadioButton();
        eggs = new javax.swing.JRadioButton();
        poliuretano = new javax.swing.JRadioButton();
        flex = new javax.swing.JRadioButton();
        foamPack = new javax.swing.JRadioButton();
        foamPackDuro = new javax.swing.JRadioButton();
        polietileno = new javax.swing.JRadioButton();
        viscoelastico = new javax.swing.JRadioButton();
        poliuretanoDuro = new javax.swing.JRadioButton();
        botonArchivo = new javax.swing.JButton();
        textSistemas1 = new javax.swing.JLabel();
        response = new javax.swing.JLabel();
        textArchivo = new javax.swing.JLabel();
        conductivo = new javax.swing.JRadioButton();
        antiestatico = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CALCULO DE COSTES DE ESPUMA | OTAYCO INDUSTRIAL ");
        setIconImage(getIconImage());

        jPanel1.setBackground(new java.awt.Color(222, 221, 221));

        textLargo.setText("Largo:");

        textoAncho.setText("Ancho:");

        textAlto.setText("Alto:");

        textLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/otayco-logo.png"))); // NOI18N

        textGeneral.setFont(new java.awt.Font("Helvetica Neue", 1, 24)); // NOI18N
        textGeneral.setForeground(new java.awt.Color(0, 204, 204));
        textGeneral.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textGeneral.setText("CALCULO DE COSTES DE ESPUMA");

        textEspumas.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        textEspumas.setForeground(new java.awt.Color(0, 204, 204));
        textEspumas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textEspumas.setText("TIPO DE ESPUMA");

        botonCalcular.setBackground(new java.awt.Color(0, 204, 204));
        botonCalcular.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        botonCalcular.setText("CALCULAR");
        botonCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCalcularActionPerformed(evt);
            }
        });

        tituloMedida.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        tituloMedida.setForeground(new java.awt.Color(0, 204, 204));
        tituloMedida.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tituloMedida.setText("MEDIDAS");

        grupoSistemas.add(mecanizado);
        mecanizado.setText("Mecanizado");

        grupoSistemas.add(ciego);
        ciego.setText("Ciego");

        grupoSistemas.add(pasante);
        pasante.setText("Pasante");

        grupoEspumas.add(eggs);
        eggs.setText("Eggs");

        grupoEspumas.add(poliuretano);
        poliuretano.setText("Poliuretano");

        grupoEspumas.add(flex);
        flex.setText("Flex");
        flex.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                flexActionPerformed(evt);
            }
        });

        grupoEspumas.add(foamPack);
        foamPack.setText("Foam Pack");
        foamPack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foamPackActionPerformed(evt);
            }
        });

        grupoEspumas.add(foamPackDuro);
        foamPackDuro.setText("Foam Pack Duro");
        foamPackDuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                foamPackDuroActionPerformed(evt);
            }
        });

        grupoEspumas.add(polietileno);
        polietileno.setText("Polietileno");
        polietileno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                polietilenoActionPerformed(evt);
            }
        });

        grupoEspumas.add(viscoelastico);
        viscoelastico.setText("Viscoelastico");
        viscoelastico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viscoelasticoActionPerformed(evt);
            }
        });

        grupoEspumas.add(poliuretanoDuro);
        poliuretanoDuro.setText("Poliuretano Duro");
        poliuretanoDuro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                poliuretanoDuroActionPerformed(evt);
            }
        });

        botonArchivo.setBackground(new java.awt.Color(0, 204, 204));
        botonArchivo.setFont(new java.awt.Font("Helvetica Neue", 1, 13)); // NOI18N
        botonArchivo.setText("SELECCIONAR RUTA");
        botonArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonArchivoActionPerformed(evt);
            }
        });

        textSistemas1.setFont(new java.awt.Font("Helvetica Neue", 1, 14)); // NOI18N
        textSistemas1.setForeground(new java.awt.Color(0, 204, 204));
        textSistemas1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textSistemas1.setText("SISTEMA A USAR");

        response.setFont(new java.awt.Font("Helvetica Neue", 2, 14)); // NOI18N
        response.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        textArchivo.setFont(new java.awt.Font("Helvetica Neue", 2, 10)); // NOI18N
        textArchivo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        textArchivo.setText("No se ha seleccionado ninguna ruta");

        grupoEspumas.add(conductivo);
        conductivo.setText("Conductivo");
        conductivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                conductivoActionPerformed(evt);
            }
        });

        grupoEspumas.add(antiestatico);
        antiestatico.setText("Antiestatico");
        antiestatico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                antiestaticoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(response, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(100, 100, 100)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(medLargo, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(medAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(46, 46, 46)
                                .addComponent(medAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(textLargo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(56, 56, 56)
                                .addComponent(textoAncho, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(69, 69, 69)
                                .addComponent(textAlto, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(tituloMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(textGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 443, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(115, 115, 115)
                                .addComponent(textLogo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(ciego)
                                .addGap(18, 18, 18)
                                .addComponent(mecanizado)
                                .addGap(18, 18, 18)
                                .addComponent(pasante))
                            .addComponent(botonCalcular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(textEspumas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(foamPackDuro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(eggs, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(poliuretano)
                                    .addComponent(polietileno))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(poliuretanoDuro)
                                    .addComponent(viscoelastico))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(flex)
                                    .addComponent(antiestatico))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(foamPack)
                                    .addComponent(conductivo))))
                        .addContainerGap(12, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(textSistemas1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(botonArchivo)
                        .addGap(156, 156, 156))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(textArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(textGeneral, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(tituloMedida, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(textoAncho)
                            .addComponent(textLargo)
                            .addComponent(textAlto))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(medAncho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medAlto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(medLargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(textLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textArchivo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textSistemas1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(botonArchivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ciego)
                    .addComponent(mecanizado)
                    .addComponent(pasante))
                .addGap(18, 18, 18)
                .addComponent(textEspumas, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(eggs)
                    .addComponent(poliuretano)
                    .addComponent(flex)
                    .addComponent(foamPack)
                    .addComponent(poliuretanoDuro))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(foamPackDuro)
                    .addComponent(polietileno)
                    .addComponent(viscoelastico)
                    .addComponent(conductivo)
                    .addComponent(antiestatico))
                .addGap(18, 18, 18)
                .addComponent(botonCalcular)
                .addGap(18, 18, 18)
                .addComponent(response, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCalcularActionPerformed
        StringBuilder sb = new StringBuilder();
        try {
            //Validacion de los campos de medidas
            if (medAncho.getText().isEmpty() || medLargo.getText().isEmpty() || medAlto.getText().isEmpty()) {
                response.setText("<html><p style='color:red'>Debes introducir todas las medidas (largo, ancho y alto).</p></html>");
                return;
            }
            
            float largo = Float.parseFloat(medLargo.getText());
            float ancho = Float.parseFloat(medAncho.getText());
            float alto = Float.parseFloat(medAlto.getText());
            if (largo <= 0 || ancho <= 0 || alto <= 0) {
                response.setText("<html><p style='color:red'>Las medidas deben ser mayores que cero.</p></html>");
                return;
            }
            
            //Validacion de los campos de tipo de espumas
            String tipoEspuma = null;
            if (eggs.isSelected()) tipoEspuma = "ALVEOLAR";
            else if (poliuretano.isSelected()) tipoEspuma = "POLIURETANO";
            else if (flex.isSelected()) tipoEspuma = "FLEX";
            else if (foamPack.isSelected()) tipoEspuma = "FOAM PACK";
            else if (foamPackDuro.isSelected()) tipoEspuma = "FOAM PACK DURO";
            else if (polietileno.isSelected()) tipoEspuma = "POLIETILENO";
            else if (viscoelastico.isSelected()) tipoEspuma = "VISCOELASTICO";
            else if (poliuretanoDuro.isSelected()) tipoEspuma = "POLIURETANO DURO";
            else if (antiestatico.isSelected()) tipoEspuma = "ANTIESTÁTICO";
            else if (conductivo.isSelected()) tipoEspuma = "CONDUCTIVO";
            if (tipoEspuma == null) {
                response.setText("<html><p style='color:red'>Debes seleccionar un tipo de espuma.</p></html>");
                return;
            }
            
            //Validacion de los campos de tipo de sistemas
            String sistema = null;
            if (ciego.isSelected()) sistema = "Espumas_Ciegas.xlsx";
            else if (mecanizado.isSelected()) sistema = "Espumas_Mecanizadas.xlsx";
            else if (pasante.isSelected()) sistema = "Espumas_Pasantes.xlsx";
            if (sistema == null) {
                response.setText("<html><p style='color:red'>Debes seleccionar un sistema a usar.</p></html>");
                return;
            }

            //Creamos el producto y servicio y montamos la ruta para leer el archivo
            Producto producto = new Producto(largo, ancho, alto, tipoEspuma, sistema);
            String excelPath = selectFile.getAbsolutePath()+File.separator+sistema;
            ProveedorService proveedorService = new ProveedorService(excelPath);

            //Mensaje principal
            sb.append("Buscando proveedores para tipo de espuma: '")
              .append(producto.getTipoEspuma())
              .append("' con medidas exactas: ")
              .append(formatearNumero(producto.getLargo())).append("x")
              .append(formatearNumero(producto.getAncho())).append("x")
              .append(formatearNumero(producto.getGrueso())).append("...\n\n");

            //PARTE 1: Buscar coincidencia exacta en el archivo
            List<Proveedor> proveedoresExactos = proveedorService.getProveedoresPorTipoEspumaYMedidas(
                    producto.getTipoEspuma(), producto);
            if (!proveedoresExactos.isEmpty()) {
                sb.append("¡Se encontraron proveedores que coinciden exactamente!\n");
                mostrarProveedores(sb, proveedoresExactos, producto);
                mostrarMejorProveedor(sb, proveedoresExactos, producto);
                mostrarMensaje(sb.toString());
                return;
            }

            //PARTE 2: En caso de no encontrar la parte 1 se busca en la parte 2 con una tolerancia del 10 por ciento tanto arriba como abajo
            sb.append("\nNo se encontraron coincidencias exactas. Buscando proveedores por tipo de espuma con tolerancia de ±10%...\n");
            List<Proveedor> proveedoresConTolerancia = proveedorService.getProveedoresPorTipoEspumaConTolerancia(
                    producto.getTipoEspuma(), producto);
            if (!proveedoresConTolerancia.isEmpty()) {
                sb.append("Proveedores encontrados con tolerancia de medidas:\n");
                mostrarProveedores(sb, proveedoresConTolerancia, producto);
                mostrarMejorProveedor(sb, proveedoresConTolerancia, producto);
                mostrarMensaje(sb.toString());
                return;
            }

            //PARTE 3: En caso de no encontrar ni parte 1 ni parte 2, dejaria de buscar ya que no encontraria nada.
            sb.append("No se encontraron proveedores con tolerancia ±10%.\nNo se ha podido ningun proveedor para estas medidas <b>"+producto.getLargo()+"x"+producto.getAncho()+"x"+producto.getGrueso()+"</b> Tipo de espuma: <b>"+producto.getTipoEspuma()+"<b>.");
            mostrarMensaje(sb.toString());
           
        } catch (NumberFormatException e) {
            response.setText("Las medidas deben ser valores numéricos válidos, usa puntos (.) para los decimales.");
        } catch (IllegalArgumentException e) {
            response.setText("Error de argumentos: " + e.getMessage() +
                    "\nVerifica que la ruta del archivo Excel es correcta y que el archivo existe.");
        } catch (IllegalStateException e) {
            response.setText("Error de formato en el Excel: Asegúrate de que el archivo contiene todas las columnas requeridas y que los encabezados son correctos.");
        } catch (NullPointerException e) {
            response.setText("ERROR: No hay ningún archivo seleccionado.");
        } catch (Exception e) {
            response.setText("Ocurrió un error inesperado: " + e.getMessage());
        }
    }//GEN-LAST:event_botonCalcularActionPerformed

    /**
     * Metodo para mostrar todos los proveedores de las caracteristicas seleccionadas
     * @param sb
     * @param proveedores
     * @param producto 
     */
    private void mostrarProveedores(StringBuilder sb, List<Proveedor> proveedores, Producto producto) {
        for (Proveedor proveedor : proveedores) {
            float volumen = producto.getVolumen();
            sb.append(String.format(
                " - %s (Tipo: %s, Medidas: %s x %s x %s, Precio: %s Eur, Volumen: %s m³, Unidades: %s)\n",
                proveedor.getNombre(), proveedor.getTipoEspuma(),
                formatearNumero(proveedor.getLargo()), formatearNumero(proveedor.getAncho()), formatearNumero(proveedor.getGrueso()),
                formatearNumero(proveedor.getPrecioUnitario()), formatearNumero(volumen),
                (proveedor.getUnidades() != null && !proveedor.getUnidades().isEmpty() ? proveedor.getUnidades() : "(No especificado)")
            ));
        }
    }

    /**
     * Metodo que te muestra el mejor proveedor con las caracteristicas que has seleccionado
     * @param sb
     * @param proveedores
     * @param producto 
     */
    private void mostrarMejorProveedor(StringBuilder sb, List<Proveedor> proveedores, Producto producto) {
        Proveedor mejor = CostCalculator.encontrarProveedorMasEconomico(proveedores);
        sb.append("\nProveedor más económico de los encontrados:\n");
        sb.append(String.format("- %s (Tipo: %s, Medidas: %s x %s x %s):\n",
            mejor.getNombre(), mejor.getTipoEspuma(),
            formatearNumero(mejor.getLargo()), formatearNumero(mejor.getAncho()), formatearNumero(mejor.getGrueso())));
        sb.append(String.format(" Precio: %s Eur\n", formatearNumero(mejor.getPrecioUnitario())));
        sb.append(String.format(" Volumen: %s m³\n", formatearNumero(producto.getVolumen())));
        sb.append(String.format(" Unidades: %s\n",
            (mejor.getUnidades() != null && !mejor.getUnidades().isEmpty() ? mejor.getUnidades() : "(No especificado)")));
    }

    /**
     * Metodo para formatear los numeros
     * @param numero
     * @return 
     */
    private String formatearNumero(float numero) {
        String numeroStr = String.format("%.6f", numero);
        numeroStr = numeroStr.replaceAll("0+$", "");
        if (numeroStr.endsWith(".")) {
            numeroStr = numeroStr.substring(0, numeroStr.length() - 1);
        }
        return numeroStr.replace(".", ",");
    }

    /**
     * Metodo que te muestra un JDialog con scroll donde esta el mensaje
     * @param mensaje 
     */
    private void mostrarMensaje(String mensaje) {
        SwingUtilities.invokeLater(() -> {
            JDialog dialog = new JDialog((Frame) null, "RESULTADO", true);
            dialog.setSize(1400, 500);
            dialog.setLocationRelativeTo(null);
            dialog.setDefaultCloseOperation(JDialog.DISPOSE_ON_CLOSE);
            JPanel mainPanel = new JPanel(new BorderLayout());
            JLabel label = new JLabel("<html><pre style='font-size:12px'>" + mensaje + "</pre></html>");
            JPanel labelPanel = new JPanel(new BorderLayout());
            labelPanel.add(label, BorderLayout.NORTH);
            labelPanel.setBackground(new Color(0, 204, 204));
            JScrollPane scrollPane = new JScrollPane(labelPanel);
            scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
            scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_AS_NEEDED);
            mainPanel.add(scrollPane, BorderLayout.CENTER);
            dialog.getContentPane().add(mainPanel);
            dialog.setVisible(true);
        });
    }

    /**
     * Metodo para obtener la ruta guardada en el archivo de configuracion.
     * @return
     */
    public static File getSavedFile() {
        File configFile = new File(CONFIG_FILE);
        if (configFile.exists()) {
            try (BufferedReader reader = new BufferedReader(new FileReader(configFile))) {
                String path = reader.readLine();
                if (path != null && !path.isEmpty()) {
                    File savedFile = new File(path);
                    if (savedFile.exists()) {
                        return savedFile;
                    }
                }
            } catch (IOException e) {
                System.err.println("Error al leer configuración: " + e.getMessage());
            }
        }
        return null;
    }

    /**
     * Metodo para seleccionar y guardar una ruta en el archivo de configuracion
     * @param parent
     * @return
     */
    public static File selectAndSaveFile(Component parent) {
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int option = fileChooser.showOpenDialog(parent);
        if (option == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
            try (FileWriter writer = new FileWriter(CONFIG_FILE)) {
                writer.write(selectedFile.getAbsolutePath());
            } catch (IOException e) {
                JOptionPane.showMessageDialog(parent, "Error al guardar la ruta: " + e.getMessage());
            }
            return selectedFile;
        }
        return null;
    }


    private void flexActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_flexActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_flexActionPerformed

    private void foamPackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foamPackActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foamPackActionPerformed

    private void foamPackDuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_foamPackDuroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_foamPackDuroActionPerformed

    private void polietilenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_polietilenoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_polietilenoActionPerformed

    private void viscoelasticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viscoelasticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_viscoelasticoActionPerformed

    private void poliuretanoDuroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_poliuretanoDuroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_poliuretanoDuroActionPerformed

    private void botonArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonArchivoActionPerformed
        selectFile = selectAndSaveFile(this);

        if (selectFile == null) {
            textArchivo.setText("(No hay ruta seleccionada)");
        } else {
            textArchivo.setText("(Carpeta Seleccionada: " + selectFile.getName() + ")");
        }
    }//GEN-LAST:event_botonArchivoActionPerformed

    private void conductivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_conductivoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_conductivoActionPerformed

    private void antiestaticoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_antiestaticoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_antiestaticoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazGraficaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazGraficaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazGraficaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazGraficaMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazGraficaMain().setVisible(true);
            }
            
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton antiestatico;
    private javax.swing.JButton botonArchivo;
    private javax.swing.JButton botonCalcular;
    private javax.swing.JRadioButton ciego;
    private javax.swing.JRadioButton conductivo;
    private javax.swing.JRadioButton eggs;
    private javax.swing.JRadioButton flex;
    private javax.swing.JRadioButton foamPack;
    private javax.swing.JRadioButton foamPackDuro;
    private javax.swing.ButtonGroup grupoEspumas;
    private javax.swing.ButtonGroup grupoSistemas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton mecanizado;
    private javax.swing.JTextField medAlto;
    private javax.swing.JTextField medAncho;
    private javax.swing.JTextField medLargo;
    private javax.swing.JRadioButton pasante;
    private javax.swing.JRadioButton polietileno;
    private javax.swing.JRadioButton poliuretano;
    private javax.swing.JRadioButton poliuretanoDuro;
    private javax.swing.JLabel response;
    private javax.swing.JLabel textAlto;
    private javax.swing.JLabel textArchivo;
    private javax.swing.JLabel textEspumas;
    private javax.swing.JLabel textGeneral;
    private javax.swing.JLabel textLargo;
    private javax.swing.JLabel textLogo;
    private javax.swing.JLabel textSistemas1;
    private javax.swing.JLabel textoAncho;
    private javax.swing.JLabel tituloMedida;
    private javax.swing.JRadioButton viscoelastico;
    // End of variables declaration//GEN-END:variables
}
